#!/usr/bin/env python3
"""Generate a flash-resident MakeCode CJK font from a 12px BDF font."""

import argparse
from pathlib import Path


GLYPH_WIDTH = 12
GLYPH_HEIGHT = 12
GLYPH_BYTES = GLYPH_HEIGHT * 2
PUNCTUATION = "，。！？；：、‘’“”（）《》〈〉【】「」—…￥·"


def gb2312_level_one():
    characters = []
    for lead in range(0xB0, 0xD8):
        for trail in range(0xA1, 0xFF):
            try:
                characters.append(bytes((lead, trail)).decode("gb2312"))
            except UnicodeDecodeError:
                pass
    if len(characters) != 3755:
        raise RuntimeError("Expected 3755 GB2312 level-one characters")
    return "".join(characters)


def parse_bdf(path):
    glyphs = {}
    encoding = None
    box = None
    bitmap = None
    with path.open("r", encoding="ascii") as source:
        for raw_line in source:
            line = raw_line.rstrip("\n")
            if line.startswith("STARTCHAR "):
                encoding = None
                box = None
                bitmap = None
            elif line.startswith("ENCODING "):
                encoding = int(line.split()[1])
            elif line.startswith("BBX "):
                box = tuple(int(value) for value in line.split()[1:])
            elif line == "BITMAP":
                bitmap = []
            elif line == "ENDCHAR":
                if encoding is not None and bitmap is not None:
                    glyphs[encoding] = (box, bitmap)
                bitmap = None
            elif bitmap is not None:
                bitmap.append(bytes.fromhex(line))
    return glyphs


def glyph_bytes(character, glyphs):
    entry = glyphs.get(ord(character))
    if entry is None:
        raise RuntimeError("Missing glyph U+%04X %s" % (ord(character), character))
    box, rows = entry
    width, height, x_offset, y_offset = box
    if width != GLYPH_WIDTH or x_offset != 0:
        raise RuntimeError("Unexpected BBX for %s: %r" % (character, box))
    if len(rows) != height or any(len(row) != 2 for row in rows):
        raise RuntimeError("Unexpected bitmap size for %s" % character)

    source_top = y_offset + height - 1
    normalized = []
    for target_row in range(GLYPH_HEIGHT):
        target_y = 9 - target_row
        source_row = source_top - target_y
        normalized.append(rows[source_row] if 0 <= source_row < height else b"\x00\x00")
    return b"".join(normalized)


def cpp_values(values, formatter, line_items):
    lines = []
    for index in range(0, len(values), line_items):
        lines.append("    " + ", ".join(formatter(value) for value in values[index:index + line_items]))
    return ",\n".join(lines)


def generate(bdf_path, output_path):
    characters = PUNCTUATION + gb2312_level_one()
    if len(set(characters)) != len(characters):
        raise RuntimeError("Character map contains duplicates")

    glyphs = parse_bdf(bdf_path)
    ordered = sorted(characters, key=ord)
    packed = b"".join(glyph_bytes(character, glyphs) for character in ordered)
    codepoints = [ord(character) for character in ordered]
    last_index = len(ordered) - 1

    output = """// Generated by tools/generate_cjk_font.py. Do not edit manually.
// Glyphs: Fusion Pixel Font 12px zh_hans, licensed under SIL OFL 1.1.
// Source: https://github.com/TakWolf/fusion-pixel-font

#include \"pxt.h\"

namespace LCD1IN8 {
static const uint16_t CJK12_CODEPOINTS[] = {
%s
};

static const uint8_t CJK12_DATA[] = {
%s
};

//%%
int cjkGlyphIndex(int codepoint) {
    int low = 0;
    int high = %d;
    while (low <= high) {
        int middle = low + (high - low) / 2;
        int value = CJK12_CODEPOINTS[middle];
        if (value == codepoint) return middle;
        if (value < codepoint) low = middle + 1;
        else high = middle - 1;
    }
    return -1;
}

//%%
int cjkGlyphByte(int glyphIndex, int byteOffset) {
    if (glyphIndex < 0 || glyphIndex > %d || byteOffset < 0 || byteOffset >= %d)
        return 0;
    return CJK12_DATA[glyphIndex * %d + byteOffset];
}
}
""" % (
        cpp_values(codepoints, lambda value: "0x%04X" % value, 12),
        cpp_values(packed, lambda value: "0x%02X" % value, 16),
        last_index,
        last_index,
        GLYPH_BYTES,
        GLYPH_BYTES,
    )
    output_path.write_text(output, encoding="utf-8")
    print("Generated %d glyphs and %d bitmap bytes" % (len(ordered), len(packed)))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("bdf", type=Path, help="Fusion Pixel 12px zh_hans BDF input")
    parser.add_argument("output", type=Path, help="Generated C++ output")
    arguments = parser.parse_args()
    if not arguments.bdf.is_file():
        parser.error("BDF input does not exist: %s" % arguments.bdf)
    if not arguments.output.parent.is_dir():
        parser.error("Output directory does not exist: %s" % arguments.output.parent)
    generate(arguments.bdf, arguments.output)


if __name__ == "__main__":
    main()
